App                 = require './app'
testDef             = require '../tests/default'
testModal           = require '../tests/modal'
testNavbar          = require '../tests/navbar'
testGrowl           = require '../tests/growl'
testDropdownButtons = require '../tests/dropdown-buttons'

testStatus          = require '../tests/status'
testDebouncer       = require '../tests/debouncer'
testBuffer          = require '../tests/buffer'
