App            = require './app'
testDef        = require '../tests/default'
testModal      = require '../tests/modal'
testNavigation = require '../tests/navigation'
testDebouncer  = require '../tests/debouncer'
testStatus     = require '../tests/status'
